### PR TITLE
Update: Improve model logic

### PR DESCRIPTION
**Pull request by johntwyman**
This PR makes a small but significant change: it now uses the volume of trackable URLs clicked within the reporting period as the basis for understanding if/when a record should be deleted. This is a better reflection of the intent of the model overall.

Tested successfully by finding an existing record with a NULL value for clicked URLs, performing the calculation, and confirming the record had been properly removed.

### CODE REVIEW

**Comment by andrew-cormick-dockery** [comment]
Honestly, I can't see the substantive change in logic here. Unless `iterator_to_array()` produces a different outcome to `getArrayCopy()` ?

**Comment by johntwyman** [comment]
> Honestly, I can't see the substantive change in logic here. Unless `iterator_to_array()` produces a different outcome to `getArrayCopy()` ?

`iterator_to_array` is just the same thing as `getArrayCopy()`.

The substantive change is newline 83 - changing from testing the mailings delivered array to the trackable URLs clicked one.

**Comment by johntwyman** [comment]
Looking at it, there's a further refinement in the code I can make, but I'll save that for next time. Right now the code is resulting in records hanging around that shouldn't, which is throwing the overall model out of whack.

**Comment by andrew-cormick-dockery** [comment]
Got it, buried in with the other non-substantive changes :D

**Pull request merged**
